#!/usr/bin/env bash

cedar-14() {
  echo "Running tests in docker (cedar-14)..."
  docker run -v $(pwd):/buildpack:ro --rm -it heroku/cedar:14 bash -c 'cp -r /buildpack /buildpack_test; cd /buildpack_test/; test/run;'
  echo ""
}

cedar() {
  echo "Running tests in docker (cedar)..."
  docker run -v $(pwd):/buildpack:ro --rm -it fabiokung/cedar bash -c 'cp -r /buildpack /buildpack_test; cd /buildpack_test/; test/run;'
}

if [ "$1" == "cedar-14" ]; then
  cedar-14
elif [ "$1" == "cedar" ]; then
  cedar
else
  cedar-14
  cedar
fi
