#!/usr/bin/env bash

mktmpdir() {
  local dir=$(mktemp -t testXXXXX)
  rm -rf $dir
  mkdir $dir
  echo $dir
}

compile() {
  local fixture=$1
  local bp_dir=$(mktmpdir)
  local build_dir=$(mktmpdir)
  local cache_dir=$(mktmpdir)
  local env_dir=$(mktmpdir)
  echo "Compiling $fixture"
  echo "in $build_dir"
  echo "(caching in $cache_dir)"
  cp -a $(pwd)/* ${bp_dir}
  cp -a ${bp_dir}/test/fixtures/$fixture/. ${build_dir}
  "$bp_dir/bin/compile" "$build_dir" "$cache_dir"
}

fixture=${1:-'stable-node'}
compile "$fixture"
