version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ruby"
      - "skip changelog"
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/resolve-version"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "rust"
      - "skip changelog"
    groups:
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
