version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ruby"
      - "skip changelog"
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github actions"
      - "skip changelog"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/resolve-version"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "rust"
      - "skip changelog"
    groups:
      libcnb:
        patterns:
          - "libcnb*"
          - "libherokubuildpack"
          - "sha2"
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/yarn2-plugins/prune-dev-dependencies"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "javascript"
      - "skip changelog"
    groups:
      javascript-dependencies:
        update-types:
          - "minor"
          - "patch"
